DATE = YEAR | YEAR "-" DIGIT DIGIT | YEAR "-" DIGIT DIGIT  "-" DIGIT DIGIT | YEAR "-" DIGIT DIGIT  "-" DIGIT DIGIT "T:" DIGIT DIGIT ":" DIGIT DIGIT TZD | YEAR "-" DIGIT DIGIT  "-" DIGIT DIGIT "T:" DIGIT DIGIT ":" DIGIT DIGIT ":" DIGIT DIGIT TZD | YEAR "-" DIGIT DIGIT  "-" DIGIT DIGIT "T:" DIGIT DIGIT ":" DIGIT DIGIT ":" DIGIT DIGIT "." NUMBER TZD ;
