/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"*\"",
    "<NUM>",
    "\"<?xml version=\\\'1.0\\\' encoding=\\\'UTF-8\\\'?>\"",
    "\"<osm version=\"",
    "\"\\\"\"",
    "\"0.6\"",
    "\" generator=\"",
    "\"Osmosis SNAPSHOT-r26564\"",
    "\">\"",
    "\"</osm>\"",
    "\"<node \"",
    "\"</node>\"",
    "\"<tag \"",
    "\"/>\"",
    "\"0\"",
    "\"-\"",
    "\"T:\"",
    "\":\"",
    "\".\"",
    "\"true\"",
    "\"false\"",
    "\" \"",
    "\"A..Z\"",
    "\"a..z\"",
    "\"Z\"",
    "\"1..9\"",
    "\"emergency=fire_hydrant\"",
    "\"fire_hydrant:type=\"",
    "\"fire_hydrant:diameter=\"",
    "\"fire_hydrant:preasure=\"",
    "\"fire_hydrant:position=\"",
    "\"underground\"",
    "\"pillar\"",
    "\"wall\"",
    "\"pond\"",
    "\"lane\"",
    "\"parking_lot\"",
    "\"sidewalk\"",
    "\"green\"",
    "\"fire_hydrant_count=\"",
    "\"highway=traffic_signals\"",
    "\"traffic_signals:sound=\"",
    "\"traffic_signals:vibration=\"",
    "\"locate\"",
    "\"walk\"",
    "\"yes\"",
    "\"no\"",
  };

}
